name: Plato Report

on:
  push:
    branches:
      - main

jobs:
  plato-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Plato
        run: npm install -g plato

      - name: Generate Plato Report
        run: plato -r -d report ./src/*.js
          
      - name: Upload Plato Report
        uses: actions/upload-artifact@v3
        with:
          name: plato-report
          path: report